config/routes.rb
DowCenter::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  
  match '/signup', to: 'users#new'

  match '/lifeguard', to: 'lifeguard_pages#home'
  match '/supervisor', to: 'supervisor_pages#home'
  match '/regular', to: 'regular_worker_pages#home'
  match '/admin', to: 'admin_pages#home'

  match '/message', to: 'admin_pages#message'
  match '/home', to: 'dow_center_pages#home'
  
  match '/reg_rules', to: 'regular_worker_pages#rules_and_protocols'
  match '/sup_rules', to: 'supervisor_pages#rules_and_protocols'
  match '/lg_rules', to: 'lifeguard_pages#rules_and_protocols'


##
#  lifeguard_path => '/lifeguard'
#  lifeguard_url => 'http://localhost:3000/lifeguard'

#  supervisor_path => '/supervisor'
#  supervisor_url => 'http://localhost:3000/supervisor'

#  regular_path => '/regular'
#  regular_url => 'http://localhost:3000/regular'

#  admin_path => '/admin'
#  admin_url => 'http://localhost:3000/admin'

  root to: 'sessions#new'


  get "admin_pages/home"
  get "admin_pages/message"
  get "admin_pages/worker_list"
  get "lifeguard_pages/home"
  get "lifeguard_pages/rules_and_protocols"
  get "supervisor_pages/home"
  get "supervisor_pages/rules_and_protocols"
  get "regular_worker_pages/home"
  get "regular_worker_pages/rules_and_protocols"
  get "dow_worker_pages/schedule"
  get "dow_center_pages/regular"
  get "dow_center_pages/supervisor"
  get "dow_center_pages/lifeguard"
  get "dow_center_pages/admin"




end
  

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :regular, :supervisor, :lifeguard, :allposition
  belongs_to :user

  validates :content, presence: true
  validates :user_id, presence: true

  default_scope order: 'microposts.created_at DESC'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :position, :password, :password_confirmation, :regular, :supervisor, :lifeguard
  has_secure_password
  has_many :microposts, dependent: :destroy


  before_save { |user| user.email = email.downcase}
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6}
  validates :password_confirmation, presence: true

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
  
end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
  layout 'admin'
  before_filter :signed_in_user, :admin_user

  def home
    
  end

  def message
  
    @microposts = current_user.microposts.build if signed_in? && current_user.admin?

  end

  def worker_list
  end

  private

  def signed_in_user
    redirect_to session_url, notice: "Please sign in." unless signed_in?
    end
  
  def admin_user
    redirect_to home_url, notice: "Unauthorized access." unless current_user.admin?
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  def handle_unverified_request
    sign_out
    super
  end

end

app/controllers/dow_center_pages_controller.rb
class DowCenterPagesController < ApplicationController

  before_filter :signed_in_user

  def regular
    
    redirect_to regular_url
    
  end

  def supervisor

    redirect_to supervisor_url

  end

  def lifeguard

    redirect_to lifeguard_url

  end


  def admin
 
    redirect_to admin_url

  end


  private
  def signed_in_user
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

end

app/controllers/dow_worker_pages_controller.rb
class DowWorkerPagesController < ApplicationController
  def schedule
  end
end

app/controllers/lifeguard_pages_controller.rb
require 'will_paginate/array'

class LifeguardPagesController < ApplicationController
  layout 'lifeguard'
  before_filter :signed_in_user, :authorized_user

  def home

    @microposts = Micropost.find_all_by_lifeguard(true).paginate(page: params[:page])

  end

  def rules_and_protocols
  end

private
  def signed_in_user
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
  
  def authorized_user
    redirect_to home_url, notice: "Unauthorized access." unless current_user.admin? or current_user.lifeguard === true
    end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :signed_in_user, :admin_user, only: [:create, :destroy]
  before_filter :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Message created!"
      redirect_to admin_url
    else
      render 'admin_pages/home'
      end
  end

  def destroy
    @micropost.destroy
    redirect_to home_url
  end

  private 
  
  def signed_in_user
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

  def admin_user
    redirect_to home.url, notice: "Unauthorized access." unless current_user.admin?
    end

  def correct_user
    @micropost = current_user.microposts.find_by_id(params[:id])
    redirect_to home_url unless current_user.admin?
  end

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
   
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      
      sign_in user
      redirect_to home_url   
      
      else
      
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
      end
end
 

  
  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/supervisor_pages_controller.rb
require 'will_paginate/array'

class SupervisorPagesController < ApplicationController
  layout 'supervisor'
  before_filter :signed_in_user, :authorized_user
  def home

    @microposts = Micropost.find_all_by_supervisor(true).paginate(page: params[:page])

  end

  def rules_and_protocols
  end

  private
  def signed_in_user
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

  def authorized_user
    redirect_to home_url, notice: "Unauthorized access." unless current_user.admin? or current_user.supervisor === true
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user, only: [:edit, :update]
  
  def new
  end

  private

  def signed_in_user
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
  
  def admin_user
    redirect_to home_url, notice:"Unauthorized access." unless user.admin?
    end
end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title, subpage_title)
    base_title = "Dow Center Worker Website"
    if page_title.empty?
      base_title
    elsif subpage_title.empty?
      "#{base_title} | #{page_title}"
    else
      "#{base_title} | #{page_title} - #{subpage_title}"

      end
    end
end

app/helpers/dow_center_pages_helper.rb
module DowCenterPagesHelper
end

app/helpers/dow_worker_pages_helper.rb
module DowWorkerPagesHelper
end

app/helpers/lifeguard_pages_helper.rb
module LifeguardPagesHelper
end

app/helpers/regular_worker_pages_helper.rb
module RegularWorkerPagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
    end

  def signed_in?
    !current_user.nil?
    end

  def current_user=(user)
    @current_user = user
    end

  def current_user
    @curren_user ||= User.find_by_remember_token(cookies[:remember_token])
    end

  def destroy
    sign_out
    redirect_to root_url
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
    end

  def store_information
    session[:return_to] = request.url
    end

end

app/helpers/supervisor_pages_helper.rb
module SupervisorPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_admin_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="containter">
      <%= link_to "Dow Center Worker Web", home_path, id: "logo" %>
      <nav>
	<ul class="nav pull-right">
	  <li><%= link_to "Home", admin_path %></li>
	  <li><%= link_to "Message", message_path %></li>
	  <li><%= link_to "Signout", signout_path, method: 'delete' %></li>
	  </ul>
	</nav>
      </div>
    </vic>
</header>

app/views/layouts/_footer.html.erb
<footer class="footer">
  
   <div class="footerContainer">
    <small> &copy; Hope College Dow Center Worker made by Hsiang Lin </small> 
    <nav>
      <ul>
	<li><a href="http://www.hope.edu">Hope College</a></li>
      </ul>
      </nav>
   </div>
    
  </footer>

app/views/layouts/_header.html.erb
<header class ="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="headContainer">
      <%= link_to "Dow Center Worker Web", home_path, id: "logo" %>
      <nav>
	<% if signed_in? %>
	<ul class="nav pull-right">
	  <li><%= link_to "Sign out", signout_path, method: 'delete' %></li>
	  </ul>
	<% end %>
	</nav>
      </div>
    </div>
  </header>

app/views/layouts/_lifeguard_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    
     <%= link_to "Dow Center Worker Web", home_path, id: "logo" %>
      <nav>
	<ul class="nav pull-right">
	  <li><%= link_to "Home", lifeguard_path %></li>
	  <li><%= link_to "Rules/Protocol", lg_rules_path %></li>
	  <li><%= link_to "Sign out", signout_path, method: 'delete'  %></li>
	  </ul>
	</nav>
    
    </div>
</header>

app/views/layouts/_regular_worker_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="containter">
      <%= link_to "Dow Center Worker Web", home_path, id: "logo" %>
      <nav>
	<ul class="nav pull-right">
	  <li><%= link_to "Home", regular_path %></li>
	  <li><%= link_to "Rules/Protocol", reg_rules_path %></li>
	  <li><%= link_to "Signout", signout_path, method: 'delete' %></li>
	</ul>
	</nav>
      </div>
    </vic>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_supervisor_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="containter">
      <%= link_to "Dow Center Worker Web", home_path, id: "logo" %>
      <nav>
	<ul class="nav pull-right">
	  <li><%= link_to "Home", supervisor_path %></li>
	  <li><%= link_to "Rules/Protocol", sup_rules_path %></li>
	  <li><%= link_to "Signout", signout_path, method: 'delete' %></li>
	  </ul>
	</nav>
      </div>
    </vic>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title), yield(:subpage_title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    </head>
  <body>

   <div class="mainContainer">
     <%= render 'layouts/admin_header' %>
     <%= yield %>
     <%= render 'layouts/footer' %>
     </div>
   </body>
  </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title), yield(:subpage_title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= stylesheet_link_tag   "custom", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    
<%= render 'layouts/header' %>
<div class="mainContainer">
    <%= yield %>
    <%= render 'layouts/footer' %>
</div>
  </body>
</html>

app/views/layouts/lifeguard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title), yield(:subpage_title)) %></title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "custom", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    </head>
  <body>

   <div class="mainContainer">
     <%= render 'layouts/lifeguard_header' %>
     <div class="container">
     <%= yield %>
     </div>
     <%= render 'layouts/footer' %>
     </div>
   
   </body>
  </html>

app/views/layouts/regularworker.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title), yield(:subpage_title)) %></title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "custom", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    </head>
  <body>
   
   <div class="mainContainer">
     <%= render 'layouts/regular_worker_header' %>
     <div class="container">
     <%= yield %>
     </div>
     <%= render 'layouts/footer' %>
  </div>

   </body>
  </html>

app/views/layouts/supervisor.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title), yield(:subpage_title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    </head>
  <body>

   <div class="mainContainer">
     <%= render 'layouts/supervisor_header' %>
     <div class="container">
     <%= yield %>
     </div>
     <%= render 'layouts/footer' %>
     </div>

   </body>
  </html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div >
  <div >
    The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li>* <%= msg %></li>
    </ul>
  </div>
<% end %>

app/views/shared/_message_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class='field'>
    <%= f.text_area :content, placeholder: "Compose new message..." %>
    </div>
  <%= f.submit "Send", class: "btn btn-large btn-primary" %>
<% end %>